CREATE DATABASE ACADEMIA;

USE ACADEMIA;

CREATE TABLE USUARIO(
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30),
	SENHA VARCHAR(15),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR(100),
	PESO FLOAT(100,1),
	ALTURA FLOAT(2.00)
);
ALTER TABLE USUARIO AUTO_INCREMENT = 100;

INSERT INTO USUARIO(NOME,SEXO,EMAIL,TELEFONE,ENDERECO,PESO,ALTURA) VALUES ('ANDRE','M','ANDREZIN@GMAIL.COM','198367367','BATATINHA - ALPHAVILLE - SAO PAULO - SP',70.00,1.70);
INSERT INTO USUARIO(NOME,SEXO,EMAIL,TELEFONE,ENDERECO,PESO,ALTURA) VALUES ('EDUARDO','M','EDUARDOZ@GMAIL.COM','183690367','MARIA ELENA - ALPHAVILLE - SAO PAULO - SP',65.00,1.50);
INSERT INTO USUARIO(NOME,SEXO,EMAIL,TELEFONE,ENDERECO,PESO,ALTURA) VALUES ('CARLOS','M','CARLINHO@GMAIL.COM','10382659','SAO MIGUEL - BELVAL - SAO PAULO - SP',87.00,1.78);
INSERT INTO USUARIO(NOME,SEXO,EMAIL,TELEFONE,ENDERECO,PESO,ALTURA) VALUES ('ANA','F','ANINHA@GMAIL.COM','10362946','SEU ZE - IMPERIAL - SAO PAULO - SP',70.00,1.67);
INSERT INTO USUARIO(NOME,SEXO,EMAIL,TELEFONE,ENDERECO,PESO,ALTURA) VALUES ('JULIA','F','JULINHA@GMAIL.COM','10439264','EUCLIDES- ENGENHO NOVO - SAO PAULO - SP',92.00,1.80);

SELECT * FROM USUARIO;

SELECT NOME, SEXO, PESO, ALTURA FROM USUARIO
WHERE SEXO = 'F';

SELECT NOME, SEXO FROM USUARIO
WHERE ENDERECO LIKE '%BELVAL%';

SELECT ID_USUARIO, NOME, SEXO, PESO, ALTURA FROM USUARIO
WHERE ENDERECO LIKE '%ALPHAVILLE%';

DROP TABLE USUARIO;


create table LOGIN(
    EMAIL INT PRIMARY KEY NOT NULL,
    SENHA VARCHAR(100)
);
SELECT * FROM LOGIN; 

create table SITE(
	ID_SITE INT auto_increment primary key not null, 
    taxabasal_site varchar (100),
    agua_site varchar(100),
    imc_site varchar(100)
);
select * from site;


CREATE TABLE PLANOS_SERVICOS(
    ID_PLANOS INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    PLANO_BRONZE VARCHAR(100),
	PLANO_PRATA VARCHAR(100),
	PLANO_OURO VARCHAR(100)
);

INSERT INTO PLANOS_SERVICOS(PLANO_BRONZE,PLANO_PRATA,PLANO_OURO) VALUES ('ESSE É O PLANO MAIS BASICO','ESSE É O PLANO MEDIANO','ESSE É O PLANO MAIS TOP');

SELECT * FROM PLANOS_SERVICOS;

SELECT PLANO_BRONZE FROM PLANOS_SERVICOS;
SELECT PLANO_PRATA FROM PLANOS_SERVICOS;
SELECT PLANO_OURO FROM PLANOS_SERVICOS;



CREATE TABLE ACADEMIA(
    CNPJ INT(14) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NOME CHAR(9),
	TELEFONE VARCHAR(30),
	EMAIL VARCHAR(30),
	ENDERECO VARCHAR(100)
    );
    ALTER TABLE USUARIO AUTO_INCREMENT = 100;
    
    INSERT INTO ACADEMIA (NOME,TELEFONE,EMAIL,ENDERECO) VALUES ('ACADEM.IA','8273027101','ACADEM.IA@GMAIL.COM','RUA BRABA - ENGENHO NOVO - BARUERI - SP');
    
SELECT * FROM ACADEMIA;

SELECT NOME AS  NOME_ACADEMIA, TELEFONE, EMAIL, ENDERECO, NOW() AS DATA_HORA FROM ACADEMIA;

CREATE TABLE PROFISSIONAL(
    ID_PROFISSIONAL INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NOME VARCHAR(30) NOT NULL,
    SEXO CHAR(1),
	TELEFONE VARCHAR(30),
	TIPO CHAR(1)
);
DROP TABLE PROFISSIONAL;
INSERT INTO PROFISSIONAL (NOME,SEXO,TELEFONE,TIPO) VALUES ('JOSE','M','294326728','F');
INSERT INTO PROFISSIONAL (NOME,SEXO,TELEFONE,TIPO) VALUES ('AMANDA','F','843271203','N');
INSERT INTO PROFISSIONAL (NOME,SEXO,TELEFONE,TIPO) VALUES ('RAEL','M','0320114098','P');

SELECT * FROM PROFISSIONAL;

SELECT NOME AS NOME_PROFISSIONAL, TIPO FROM PROFISSIONAL; 

CREATE TABLE LISTA_TREINO(
ID_LISTA_TREINO INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
MUSCULACAO VARCHAR(100),
EMAGRECIMENTO VARCHAR(100),
MOVIMENTACAO VARCHAR(100)
);

INSERT INTO LISTA_TREINO (MUSCULACAO,EMAGRECIMENTO,MOVIMENTACAO) VALUES ('DORSAL','DANÇA','CORRIDA');
INSERT INTO LISTA_TREINO (MUSCULACAO,EMAGRECIMENTO,MOVIMENTACAO) VALUES ('PERNAS','HIT','YOGA');
INSERT INTO LISTA_TREINO (MUSCULACAO,EMAGRECIMENTO,MOVIMENTACAO) VALUES ('ABDOMEN','PULAR CORDA','RUN');

SELECT * FROM LISTA_TREINO;


CREATE TABLE CRIAR(
ID_LISTA_TREINO INT,
CNPJ INT,
FOREIGN KEY (ID_LISTA_TREINO) REFERENCES LISTA_TREINO(ID_LISTA_TREINO),
FOREIGN KEY (CNPJ) REFERENCES ACADEMIA(CNPJ)
);

